# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Childress Blog
email: cameronc@sumoc.com
phone: +1 678.637.5072
description: > # this means to ignore newlines until "baseurl:"
  Entrepreneur and software developer. I make things. Occasionally post here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cameroncf.github.io" # the base hostname & protocol for your site
twitter_username: cameronc
github_username:  cameroncf

# Build settings
markdown: kramdown
theme: jekyll-theme-leap-day # https://github.com/pages-themes/leap-day
